Repository wantedPreOnboarding/19_04th_messenger, pull requests merged in 2022-02, with the labels that each got.

#22 [수임] Modify - Theme 수정 , Add-메세지 전송 박스 스타일링 및 기능 구현
  src/App.tsx
  src/components/sendbox/SendBox.styled.ts
  src/components/sendbox/SendBox.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: enhancement, style

#23 [영종] Add - eslint 수정, Chat 전역상태 설계, NextId 생성함수 구현
  .eslintrc.js
  public/assets/images/defaultUserImg.png
  src/App.tsx
  src/data/chat.ts
  src/index.tsx
  src/store/messenger.ts
  src/store/slices/auth.ts
  src/store/slices/chat.ts
  src/store/slices/index.ts
  src/store/store.ts
  src/utils/generateNextId.test.ts
  src/utils/generateNextId.ts
Labels: enhancement

#24 Fix sandBox 폴더 삭제
  src/components/sendbox/SendBox.styled.ts
  src/components/sendbox/SendBox.tsx
Labels: bug

#27 [다빈] Add - 삭제 모달, 삭제 답장 버튼 마크업 및 스타일링, 테마 컬러 추가
  public/assets/images/deleteBtn.svg
  public/assets/images/replyBtn.svg
  src/components/DelModal/DelModal.styled.tsx
  src/components/DelModal/DelModal.tsx
  src/components/DelReplyBtn/DelReplyBtn.styled.tsx
  src/components/DelReplyBtn/DelReplyBtn.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: enhancement, style

#25 [영종] Add - Header 컴포넌트 구현 완료, hexToRGB 유틸함수 추가
  .env
  public/assets/images/arrowIcon.svg
  public/assets/images/moreIcon.svg
  src/App.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/Header.tsx
  src/components/Header/Header.type.ts
  src/components/index.ts
  src/utils/hexToRGB.test.ts
  src/utils/hexToRGB.ts
  src/utils/index.ts
Labels: enhancement

#31 [수임] Add - 공통 utils 함수 분리 & 채팅 입력시 create 리듀서 연결 및 utils 함수 연결 & 폴더 이름 오류로 인한 재 커밋
  src/components/SendBox/SendBox.styled.ts
  src/components/SendBox/SendBox.tsx
  src/utils/enterSubmitCheck.ts
  src/utils/index.ts
  src/utils/isEmpty.ts
  src/utils/textareaHeightHandler.ts
Labels: bug, enhancement

#32 [수임] Add - reply reducer , 공지 토스트 기능 추가 Modify redux store 구조 변경 및 sendbox 관리 방법 변경
  src/components/SendBox/NoticeToast.styled.ts
  src/components/SendBox/NoticeToast.tsx
  src/components/SendBox/SendBox.styled.ts
  src/components/SendBox/SendBox.tsx
  src/components/index.ts
  src/store/slices/chat.ts
  src/utils/enterSubmitCheck.ts
  src/utils/index.ts
  src/utils/isEmpty.ts
  src/utils/isStringEmpty.test.ts
  src/utils/isStringEmpty.ts
  src/utils/startEndWhiteSpaceRemove.test.ts
  src/utils/startEndWhiteSpaceRemove.ts
Labels: enhancement, style

#34 [송현] Add - 대화 목록, 대화 목록 아이템 레이아웃
  src/components/ChatList/ChatList.styled.ts
  src/components/ChatList/ChatList.tsx
  src/components/ChatList/ChatListItem/ChatListItem.styled.ts
  src/components/ChatList/ChatListItem/ChatListItem.tsx
  src/components/ChatList/ChatListItem/ChatListItem.type.ts
  src/components/README.md
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: style

#37 Add 답장 버튼 챗리스트 연결 후 리듀서 연결 Modify 토스트 모달 중복 호출 방지
  src/components/DelReplyBtn/DelReplyBtn.styled.tsx
  src/components/DelReplyBtn/DelReplyBtn.tsx
  src/components/InputBox/InputBox.tsx
Labels: enhancement

#38 [송현] Add - 대화 목록 시간 표시 기능 구현
  src/components/ChatList/ChatList.styled.ts
  src/components/ChatList/ChatList.tsx
  src/components/ChatList/ChatListItem/ChatListItem.styled.ts
  src/components/ChatList/ChatListItem/ChatListItem.tsx
  src/components/ChatList/ChatListItem/ChatListItem.type.ts
  src/data/chat.ts
Labels: enhancement

#44 [다빈] Add - 삭제 모달, 삭제 버튼 기능
  src/components/DelModal/DelModal.styled.tsx
  src/components/DelModal/DelModal.tsx
  src/components/DelModal/DelModal.type.ts
  src/components/DelReplyBtn/DelReplyBtn.styled.tsx
  src/components/DelReplyBtn/DelReplyBtn.tsx
  src/store/slices/modal.ts
Labels: enhancement

#45 [수임] Add - Login 스타일 적용 Modify - Login 컴포넌트에서 페이지로 이동
  src/components/Login/Login.styled.ts
  src/components/index.ts
  src/pages/Login/Login.styled.ts
  src/pages/Login/Login.tsx
  src/pages/index.ts
Labels: enhancement

#54 [수임] Add - 로그인 데이터 연결 Modify 메세지 작성 리듀서 수정
  src/components/Login/Login.styled.ts
  src/pages/Login/Login.styled.ts
  src/pages/Login/Login.tsx
  src/store/slices/chat.ts
Labels: enhancement, style

#56 [영종] - Add, Fix 날짜 형식 함수, scroll 동작 오류 해결
  README.md
  src/components/ChatList/ChatList.tsx
  src/components/ChatList/ChatListItem/ChatListItem.tsx
  src/data/chat.ts
  src/hooks/useScrollBottom.ts
  src/pages/ChatRoom/ChatRoom.tsx
  src/styles/globalStyles.ts
  src/utils/date.test.ts
  src/utils/date.ts
  src/utils/index.ts
Labels: documentation, enhancement

#57 [다빈] Add - 답장, 삭제 버튼과 삭제 모달 연결, 글자 자르기 유틸, 폰트 확대
  src/App.tsx
  src/components/ChatList/ChatListItem/ChatListItem.styled.ts
  src/components/ChatList/ChatListItem/ChatListItem.tsx
  src/components/DelModal/DelModal.styled.tsx
  src/components/DelModal/DelModal.tsx
  src/components/DelReplyBtn/DelReplyBtn.styled.tsx
  src/components/DelReplyBtn/DelReplyBtn.tsx
  src/components/Header/Header.styled.ts
  src/pages/ChatRoom/ChatRoom.tsx
  src/styles/theme.ts
  src/utils/sliceMessage.test.ts
  src/utils/sliceMessage.ts
  yarn.lock
Labels: enhancement, style

#62 Add - 메시지 hover 시 버튼 노출
  src/components/ChatList/ChatListItem/ChatListItem.styled.ts
  src/components/ChatList/ChatListItem/ChatListItem.tsx
  src/components/DelReplyBtn/DelReplyBtn.styled.tsx
  src/components/DelReplyBtn/DelReplyBtn.tsx
Labels: enhancement, style
